"""privacy_consent_and_report_revisions

Revision ID: 3f782f034deb
Revises: 766aed0ea62c
Create Date: 2026-09-07 21:09:46.759461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f782f034deb'
down_revision: Union[str, Sequence[str], None] = '766aed0ea62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_report_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['ai_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_report_revisions_report_id'), 'ai_report_revisions', ['report_id'], unique=False)
    op.add_column('professionals', sa.Column('analytics_consent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('professionals', sa.Column('analytics_consent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('professionals', sa.Column('analytics_consent_version', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professionals', 'analytics_consent_version')
    op.drop_column('professionals', 'analytics_consent_at')
    op.drop_column('professionals', 'analytics_consent')
    op.drop_index(op.f('ix_ai_report_revisions_report_id'), table_name='ai_report_revisions')
    op.drop_table('ai_report_revisions')
    # ### end Alembic commands ###
